# Default properties for the WooCommerce module
glamaya:
  sync:
    woocommerce:
      api:
        # --- IMPORTANT ---
        # These are environment-specific secrets and should be defined here or in a profile.
        baseUrl: http://your-woocommerce-store.com
        consumerKey: ck_your_consumer_key
        consumerSecret: cs_your_consumer_secret
        # Max response size to buffer in memory (in bytes).
        max-in-memory-size: 10485760 # 10MB
        # Timeout for waiting for a response from the server (in milliseconds).
        response-timeout-in-millis: 30000 # 30 seconds
        endpoint-configs:
          WOOCOMMERCE_ORDER:
            enable: false
            reset-on-startup: false
            init-page: 1
            page-size: 10
            fetch-duration-ms:
              active: 1000
              passive: 60000
            query-url: "/wp-json/wc/v3/orders"
          WOOCOMMERCE_USER:
            enable: false
            reset-on-startup: false
            init-page: 1
            page-size: 10
            fetch-duration-ms:
              active: 1000
              passive: 60000
            query-url: "/wp-json/wc/v3/customers"
